cache: apt
language: c
install:
# We're using Juju (Arch Linux). It's actually pretty nice.
  - PATH=$PWD/bin:$PATH
  - juju -f echo ':)'
  - echo Server = 'https://mirrors.kernel.org/archlinux/$repo/os/$arch' | juju -f tee -a /etc/pacman.d/mirrorlist
  - yes | juju -f pacman -Syy
  - yes | juju -f pacman -S arch-install-scripts git
  - juju -f pacman --noconfirm -S base-devel 
  - find . -name arch-chroot -exec cp {} $PWD/bin \;
  - juju -f echo ':)'
  - juju -f juju -b
